version: '3.3'
services:

  app:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
      args:
        - UID=${UID}
        - USER_NAME=${USER_NAME}
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ../:/var/www:delegated
       - ../storage/log/profiles:/tmp/profiles:delegated
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini:delegated
       - ./php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:delegated
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8079:80"
      - "442:443"
    volumes:
      - ../:/var/www:delegated
      - ../docker/nginx/conf.d/:/etc/nginx/conf.d/:delegated
    networks:
      - app-network

  db:
    image: mariadb:latest
    restart: unless-stopped
    tty: true
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: videodb
      MYSQL_ROOT_PASSWORD: 12345
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ../docker/mysql/my.cnf:/etc/mysql/my.cnf:delegated
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
